import type { Metadata } from "next";
import { Bebas_Neue, Roboto } from "next/font/google";
import { Providers } from "@/providers";
import "../styles/globals.css";

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
  display: "swap",
});

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Streaming App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bebas.variable} ${roboto.variable}`}
      suppressHydrationWarning
    >
      <body className="font-sans bg-black text-white">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
