export const DEFAULT_REDIS_TTL_SECONDS = 3600;

export type REDIS_PREFIX = (typeof REDIS_PREFIX)[keyof typeof REDIS_PREFIX];

export const REDIS_PREFIX = {
  SIGNATURE: 'SIGN',
  RATE_LIMIT: 'RATE',
  CACHE: 'CACHE',
  AUTH_SESSION: 'AUTH_SESSION',
  BLACKLIST: 'BLACKLIST',
  STREAM_SESSION: 'STREAM_SESSION',
  RESEND_VERIFICATION_EMAIL: 'RESEND_VERIFICATION_EMAIL',
  CHAT_HISTORY: 'CHAT_HISTORY',
  CHAT_PIN_MESSAGE: 'CHAT_PIN_MESSAGE',
} as const;

export const REDIS_CLIENT = 'REDIS_CLIENT';
